#日期时间函数
SELECT 
YEAR(CURDATE()),#返回年份
HOUR(CURTIME()),#返回时间（小时）
MONTHNAME(CURDATE()),#返回月份
DAYNAME(CURDATE()),#返回星期几
WEEKDAY(CURDATE()),#返回周几（注意：返回的是偏移量，0123456）
QUARTER(CURDATE()),#返回季节（1~4）
WEEK(CURDATE()),#返回一年中的第几周
DAYOFYEAR(CURDATE()),#返回这是一年当中的第几天
DAYOFMONTH(CURDATE()),#返回这是一月当中的第几天
DAYOFWEEK(CURDATE())#返回周几（注意：从周日开始，周日是1）
FROM DUAL;

#日期操作函数
SELECT
EXTRACT(YEAR_MONTH FROM NOW())#返回年月
FROM DUAL;
     
#时间转换秒钟函数
SELECT TIME_TO_SEC(NOW()),#时间转换秒数
SEC_TO_TIME('59626')#秒数转换时间
FROM DUAL;

#计算日期时间函数
SELECT DATE_ADD(CURDATE(),INTERVAL '1_10' YEAR_MONTH),
#计算与当前时间相隔interval时间段的日期
DATE_ADD(CURDATE(),INTERVAL '-1_-10' YEAR_MONTH)
#也可传入负数，使其相减
FROM DUAL;

SELECT ADDTIME(NOW(),'1:1')#计算与t1间隔t2的时间（此为一小时一分）
FROM DUAL;

SELECT MAKETIME(10,50,10)
FROM DUAL;

SELECT NOW()+0
FROM DUAL;

SELECT DATE_FORMAT(CURDATE(),'%Y-%m-%d')
FROM DUAL;

SELECT STR_TO_DATE('21-12-28','%y-%m-%d')
FROM DUAL;
#获取所需国家的日期格式
#根据获取到的国家日期格式去格式时间
SELECT DATE_FORMAT(CURDATE(),GET_FORMAT(DATE,'USA'))
FROM DUAL;